version: '3.8'

services:
  akab:
    image: akab-mcp:latest
    container_name: akab-mcp-claude
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATA_DIR=/data
      - KRILL_DIR=/krill
    volumes:
      - ./data:/data
      - ../krill/data:/krill
    stdin_open: true
    tty: true
    restart: unless-stopped
